name: sequence_analysis_dev
channels:
  - conda-forge
  - openalea3/label/dev
  - openalea3
dependencies:
  - python
  - pip
  - boost
  - matplotlib-base
  - openalea.stat_tool
  - compilers
  - pip:
      - -e '..[test,dev,doc]'
